// Complete trading curriculum for the Learn Academy.
// Each lesson has a real explanation, key points, a real-world example,
// and a mini quiz with an explanation. Content is educational only and
// never presents any pattern or strategy as a guaranteed signal.

function L(id, title, explanation, keyPoints, example, quiz) {
  return { id, title, explanation, keyPoints, example, quiz };
}

export const COURSES = [
  // ─────────────────────────────────────────────
  // COURSE 1 — TRADING FUNDAMENTALS
  // ─────────────────────────────────────────────
  {
    id: 'fundamentals',
    title: 'Trading Fundamentals',
    icon: '📚',
    color: 'blue',
    description: 'The core vocabulary and mechanics every trader must understand before risking a single rupee.',
    lessons: [
      L('fund-1', 'What is Trading?',
        'Trading is the act of buying and selling financial instruments to profit from price changes. You exchange assets on a market, aiming to sell higher than you bought (or buy back lower if short).',
        ['Trading is about price movement, not ownership of a business long-term.', 'Every trade has a buyer and a seller with opposite expectations.', 'Profit comes from being on the correct side of a price move — never guaranteed.'],
        'A trader buys 1 share of AAPL at $220 and sells it at $230, profiting $10 from the price rise (minus fees).',
        { q: 'What is the primary goal of trading?', options: ['To own companies forever', 'To profit from price changes', 'To avoid all risk', 'To guarantee income'], correct: 1, explain: 'Trading aims to profit from price movement, not to hold assets indefinitely.' }),
      L('fund-2', 'Investing vs Trading',
        'Investing holds assets for years to benefit from growth and compounding. Trading holds for minutes to weeks, aiming to capture shorter price moves. Trading requires more active management and discipline.',
        ['Investing = long time horizon, low frequency.', 'Trading = short time horizon, high frequency.', 'Trading demands tighter risk control because moves are smaller and faster.'],
        'An investor buys Reliance and holds 5 years; a day trader buys Reliance at 9:30 AM and exits by 3:25 PM.',
        { q: 'Which is true about trading vs investing?', options: ['Trading needs less discipline', 'Trading has a shorter time horizon', 'Investing is the same as scalping', 'Trading never uses charts'], correct: 1, explain: 'Trading operates on a much shorter time horizon than investing.' }),
      L('fund-3', 'Stocks',
        'A stock is a share of ownership in a company. Its price moves based on earnings, news, and supply/demand for the shares.',
        ['Stock price reflects market expectations of future value.', 'Liquidity varies — large caps are easier to trade than small caps.', 'Earnings and news can cause sharp gaps.'],
        'TCS announces strong results; the stock gaps up at open as buyers rush in.',
        { q: 'What does a stock price mainly reflect?', options: ['The CEO mood', 'Market expectations of future value', 'The number of employees', 'Fixed government rates'], correct: 1, explain: 'Stock prices are driven by collective expectations of future value.' }),
      L('fund-4', 'Crypto',
        'Cryptocurrencies are digital assets traded 24/7. They tend to be more volatile than stocks and are driven by sentiment, adoption news, and liquidity.',
        ['Crypto markets never close — risk runs overnight.', 'High volatility means wider stops and smaller position sizes.', 'Regulation and exchange risk are real considerations.'],
        'BTC rallies 8% in a few hours on ETF approval news, then drops 5% the next day.',
        { q: 'A key difference of crypto markets is:', options: ['They close on weekends', 'They trade 24/7', 'They have no volatility', 'They never gap'], correct: 1, explain: 'Crypto trades around the clock, 7 days a week.' }),
      L('fund-5', 'Forex',
        'Forex (foreign exchange) is trading currency pairs like EUR/USD. The first currency is bought, the second is sold. Forex is driven by interest rates, economics, and flows.',
        ['Pairs are quoted as base/quote (EUR/USD = how many USD for 1 EUR).', 'Major pairs are very liquid with tight spreads.', 'News like NFP or rate decisions can cause sharp moves.'],
        'EUR/USD moves from 1.0850 to 1.0900 — the Euro strengthened against the Dollar.',
        { q: 'In EUR/USD, if the price rises, the ___ strengthens.', options: ['USD', 'EUR', 'JPY', 'GBP'], correct: 1, explain: 'A rising EUR/USD means the Euro is strengthening versus the Dollar.' }),
      L('fund-6', 'Futures & Leverage',
        'Futures are contracts to buy/sell an asset at a set price on a future date. Leverage lets you control a large position with a small deposit (margin), amplifying both gains and losses.',
        ['Leverage multiplies risk, not just reward.', 'Margin calls can force closure of positions.', 'Futures can expire — check contract dates.'],
        'With 10x leverage, a 1% price move becomes a 10% gain or loss on your margin.',
        { q: 'Leverage primarily:', options: ['Removes all risk', 'Amplifies gains and losses', 'Guarantees profit', 'Lowers fees'], correct: 1, explain: 'Leverage amplifies both gains and losses proportionally.' }),
      L('fund-7', 'Bid / Ask / Spread',
        'The bid is the highest price a buyer will pay; the ask is the lowest a seller will accept. The spread is the gap between them. You buy at the ask and sell at the bid.',
        ['Tight spread = liquid market.', 'Wide spread = higher cost to enter/exit.', 'Spread is a hidden cost on every trade.'],
        'A stock shows bid $100.00 / ask $100.05. You buy at $100.05 and immediately could only sell at $100.00 — a 5 cent cost.',
        { q: 'You buy at the ___ and sell at the ___.', options: ['bid / ask', 'ask / bid', 'open / close', 'limit / market'], correct: 1, explain: 'Buyers pay the ask; sellers receive the bid.' }),
      L('fund-8', 'Market vs Limit vs Stop Orders',
        'A market order executes immediately at the best available price. A limit order executes only at your specified price or better. A stop order becomes a market order once a trigger price is hit.',
        ['Market = speed, not price certainty.', 'Limit = price control, not execution certainty.', 'Stop = used for exits (stop loss) and breakouts.'],
        'You place a limit buy at $100; price must fall to $100 to fill. A market buy fills instantly at the ask.',
        { q: 'Which order guarantees price but not execution?', options: ['Market', 'Limit', 'Stop', 'Trailing'], correct: 1, explain: 'A limit order controls price but may never fill.' }),
      L('fund-9', 'Liquidity & Volatility',
        'Liquidity is how easily an asset can be traded without moving the price. Volatility is how much price moves over time. Liquid, volatile markets are easiest to trade.',
        ['Low liquidity = slippage and gaps.', 'High volatility = bigger opportunity AND bigger risk.', 'Avoid trading illiquid assets with size.'],
        'A small-cap stock jumps 15% on a $5,000 order because few shares are available — low liquidity.',
        { q: 'Slippage is most likely in:', options: ['Highly liquid markets', 'Illiquid markets', 'Index funds only', 'Government bonds only'], correct: 1, explain: 'Illiquid markets cause slippage because orders move the price.' }),
      L('fund-10', 'Long vs Short',
        'Going long means buying first to profit from a rise. Going short means selling first (borrowing) to profit from a fall. Both can lose money if the price moves against you.',
        ['Long profit = sell higher than you bought.', 'Short profit = buy back lower than you sold.', 'Shorts have theoretically unlimited loss risk.'],
        'You short TSLA at $250; price falls to $230; you buy back, profiting $20 per share.',
        { q: 'A short trade profits when price:', options: ['Rises', 'Falls', 'Stays flat', 'Gaps up'], correct: 1, explain: 'Shorts profit from a decline in price.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 2 — CANDLESTICK MASTERY
  // ─────────────────────────────────────────────
  {
    id: 'candlesticks',
    title: 'Candlestick Mastery',
    icon: '🕯️',
    color: 'amber',
    description: 'Read the story of price through candles — structure, psychology, and context. No pattern is a guaranteed signal.',
    lessons: [
      L('cand-1', 'Anatomy of a Candle',
        'A candle shows Open, High, Low, and Close for a period. The body is between open and close; the wicks (shadows) show the extremes. Bullish candles close above open; bearish close below.',
        ['Body = sentiment strength between open and close.', 'Wicks = rejection / volatility at extremes.', 'Color shows who won the period.'],
        'A candle opens 100, spikes to 105, drops to 98, closes 103 — a green body 100→103 with wicks to 98 and 105.',
        { q: 'The body of a candle is between:', options: ['High and Low', 'Open and Close', 'Bid and Ask', 'Two days'], correct: 1, explain: 'The body spans the open-to-close range.' }),
      L('cand-2', 'Bullish vs Bearish Candle',
        'A bullish candle closes higher than it opens (buyers won). A bearish candle closes lower than it opens (sellers won). The size of the body shows conviction.',
        ['Long body = strong move.', 'Small body = indecision.', 'Always read candles in context, not isolation.'],
        'A long green candle after a downtrend may signal buyers stepping in — but needs confirmation.',
        { q: 'A candle that closes well above its open is:', options: ['Bearish', 'Bullish', 'Neutral always', 'A doji'], correct: 1, explain: 'Closing above open indicates buyers controlled the period.' }),
      L('cand-3', 'Doji — Indecision',
        'A doji has open and close nearly equal, forming a thin body. It signals indecision — neither buyers nor sellers won. In context (after a long run) it can hint at reversal, but alone it means nothing.',
        ['Doji = balance of power.', 'Needs context to matter.', 'Not a signal by itself.'],
        'After a 10-day rally, a doji forms — possible exhaustion, but only confirmed by a follow-through bearish candle.',
        { q: 'A doji mainly represents:', options: ['Strong bullishness', 'Indecision', 'Guaranteed reversal', 'High volume'], correct: 1, explain: 'A doji signals indecision, not a guaranteed reversal.' }),
      L('cand-4', 'Hammer',
        'A hammer has a small body near the top, a long lower wick (at least 2x the body), and little/no upper wick. It shows sellers pushed price down but buyers rejected it back up. Most meaningful near support in a downtrend.',
        ['Long lower wick = buyers rejected lows.', 'Must appear after a decline to matter.', 'Confirmation = next candle closes higher.'],
        'A stock in a downtrend prints a hammer at a known support; the next candle closes green — a potential reversal setup.',
        { q: 'A hammer is most meaningful:', options: ['At the top of an uptrend', 'After a decline near support', 'In the middle of a range', 'Anywhere, always'], correct: 1, explain: 'Hammers are meaningful after declines, where rejection of lows can reverse price.' }),
      L('cand-5', 'Shooting Star',
        'A shooting star has a small body near the bottom, a long upper wick, and little lower wick. It shows buyers pushed price up but sellers rejected it. Most meaningful near resistance in an uptrend.',
        ['Long upper wick = buyers rejected at highs.', 'Context: after a rally, near resistance.', 'Confirm with a follow-through bearish candle.'],
        'After a rally into resistance, a shooting star forms; next candle drops — potential reversal.',
        { q: 'A shooting star signals potential reversal when it appears:', options: ['Near support in a downtrend', 'Near resistance in an uptrend', 'In a flat range', 'After a gap down'], correct: 1, explain: 'Shooting stars near resistance in uptrends can signal rejection.' }),
      L('cand-6', 'Bullish Engulfing',
        'A bullish engulfing pattern has a small bearish candle followed by a large bullish candle whose body fully covers the prior body. It shows a shift of control to buyers. Most meaningful in a downtrend or at support.',
        ['Body must engulf the previous body.', 'Shows aggressive buying.', 'Needs context — stronger at support.'],
        'In a downtrend, a small red candle is engulfed by a large green one at support — a potential reversal.',
        { q: 'In a bullish engulfing, the second candle body:', options: ['Is smaller than the first', 'Fully covers the first body', 'Is always a doji', 'Must be bearish'], correct: 1, explain: 'The bullish candle body must engulf the prior bearish body.' }),
      L('cand-7', 'Bearish Engulfing',
        'A bearish engulfing has a small bullish candle followed by a large bearish candle that engulfs it. It shows sellers taking control. Most meaningful in an uptrend or at resistance.',
        ['Large bearish body engulfs prior body.', 'Shows aggressive selling.', 'Stronger at resistance.'],
        'After a rally into resistance, a small green candle is engulfed by a large red one — potential reversal.',
        { q: 'A bearish engulfing is strongest:', options: ['At support in a downtrend', 'At resistance in an uptrend', 'In a tight range', 'After a huge gap up already'], correct: 1, explain: 'Bearish engulfings near resistance in uptrends carry more weight.' }),
      L('cand-8', 'Morning Star',
        'A three-candle reversal pattern: a large bearish candle, a small indecision candle (doji/spinning top) showing exhaustion, then a large bullish candle closing well into the first candle body. It suggests a downtrend may be reversing up.',
        ['Three candles: down, indecision, up.', 'The third candle should reclaim much of the first.', 'Confirm with structure, not just the pattern.'],
        'After a downtrend: big red, small doji, big green reclaiming the red — a morning star.',
        { q: 'A morning star appears in a:', options: ['Downtrend, potential bottom', 'Uptrend, potential top', 'Range, no meaning', 'Bull flag'], correct: 0, explain: 'Morning stars form in downtrends and suggest potential upside reversal.' }),
      L('cand-9', 'Evening Star',
        'The mirror of the morning star: a large bullish candle, a small indecision candle, then a large bearish candle reclaiming the first. Suggests an uptrend may be reversing down.',
        ['Three candles: up, indecision, down.', 'Third candle reclaims the first.', 'Confirm with structure.'],
        'After a rally: big green, small doji, big red — an evening star.',
        { q: 'An evening star suggests:', options: ['Bullish continuation', 'Potential top after an uptrend', 'A breakout', 'A hammer'], correct: 1, explain: 'Evening stars suggest a potential top after an uptrend.' }),
      L('cand-10', 'Three White Soldiers / Three Black Crows',
        'Three White Soldiers = three long bullish candles in a row, each closing higher, after a downtrend — sustained buying. Three Black Crows = three long bearish candles after an uptrend — sustained selling. Both show conviction, not guaranteed continuation.',
        ['Three consecutive strong candles one direction.', 'Show sustained momentum.', 'Can also be exhaustion if extended.'],
        'After a downtrend, three strong green candles push higher — Three White Soldiers.',
        { q: 'Three White Soldiers consist of:', options: ['Three dojis', 'Three strong bullish candles', 'Three bearish candles', 'One candle'], correct: 1, explain: 'Three White Soldiers are three consecutive strong bullish candles.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 3 — PRICE ACTION
  // ─────────────────────────────────────────────
  {
    id: 'price-action',
    title: 'Price Action',
    icon: '📈',
    color: 'green',
    description: 'Read raw price without indicators. The most important skill in trading — structure, trends, and shifts.',
    lessons: [
      L('pa-1', 'What is Price Action?',
        'Price action is the study of how price moves on a chart, using only the price itself — no indicators. It focuses on structure, momentum, and the story of buyers vs sellers.',
        ['Price discounts all news and expectations.', 'Structure (HH/HL) defines trend.', 'Context beats any single pattern.'],
        'A trader ignores RSI and watches only how price makes higher highs and higher lows to define an uptrend.',
        { q: 'Price action analysis relies on:', options: ['Indicators only', 'Raw price movement', 'News headlines only', 'Moving averages always'], correct: 1, explain: 'Price action uses raw price, not indicators.' }),
      L('pa-2', 'Market Structure: HH, HL, LH, LL',
        'An uptrend makes Higher Highs (HH) and Higher Lows (HL). A downtrend makes Lower Highs (LH) and Lower Lows (LL). These define trend objectively.',
        ['HH + HL = uptrend.', 'LH + LL = downtrend.', 'Equal highs/lows = range / consolidation.'],
        'A stock makes 100→110→105→115→112→120 — each high and low higher than the last: an uptrend.',
        { q: 'Higher Highs and Higher Lows define a:', options: ['Downtrend', 'Uptrend', 'Range', 'Reversal'], correct: 1, explain: 'HH + HL structure defines an uptrend.' }),
      L('pa-3', 'Break of Structure (BOS)',
        'A Break of Structure occurs when price breaks above a prior swing high (in an uptrend) or below a prior swing low (in a downtrend), confirming continuation of the trend.',
        ['BOS confirms trend continuation.', 'Needs a clear swing point to break.', 'A close beyond the swing is stronger than a wick.'],
        'In an uptrend, price breaks above the last swing high of 115, confirming the uptrend continues.',
        { q: 'A bullish BOS is price breaking:', options: ['Below a prior low', 'Above a prior high', 'Through a moving average', 'Into a doji'], correct: 1, explain: 'A bullish break of structure breaks above a prior swing high.' }),
      L('pa-4', 'Change of Character (CHoCH)',
        'A Change of Character is the first sign of trend shift: in an uptrend, price makes a Lower Low (breaks the last HL). It suggests the trend may be reversing. It is a warning, not a guaranteed reversal.',
        ['CHoCH = first counter-trend structure.', 'Often precedes a full reversal.', 'Confirm with a new BOS in the opposite direction.'],
        'In an uptrend, price breaks below the last higher low — a CHoCH warning that sellers may be taking over.',
        { q: 'A CHoCH in an uptrend is when price:', options: ['Makes a new HH', 'Breaks the last HL (lower low)', 'Stays flat', 'Gaps up'], correct: 1, explain: 'A CHoCH is the first lower low, signalling possible trend shift.' }),
      L('pa-5', 'Breakout vs Fakeout',
        'A breakout is price moving beyond a key level with conviction (close + volume). A fakeout is a move beyond a level that quickly reverses back — trapping breakout traders. Confirmation separates them.',
        ['Breakout = sustained move beyond level.', 'Fakeout = quick rejection back through.', 'Wait for a retest or close to confirm.'],
        'A stock breaks resistance at 100, spikes to 102, then falls back below 100 — a fakeout that trapped buyers.',
        { q: 'A fakeout is:', options: ['A sustained breakout', 'A quick move beyond a level that reverses', 'A doji', 'A gap up'], correct: 1, explain: 'A fakeout breaks a level then reverses, trapping traders.' }),
      L('pa-6', 'Retest',
        'After a breakout, price often returns to the broken level. A successful retest holds the level (former resistance becomes support) and offers a lower-risk entry. A failed retest invalidates the setup.',
        ['Broken resistance often becomes support.', 'Retest offers a defined, lower-risk entry.', 'Failure to hold = invalidation.'],
        'Price breaks resistance at 100, pulls back to 100, holds, and resumes up — a textbook retest entry.',
        { q: 'A successful retest:', options: ['Breaks the level again immediately', 'Holds the broken level', 'Is always a loss', 'Requires volume spike'], correct: 1, explain: 'A successful retest holds the broken level, confirming it as new support/resistance.' }),
      L('pa-7', 'Impulse & Correction',
        'Markets move in impulses (strong directional moves with the trend) and corrections (counter-trend pullbacks). Impulses show momentum; corrections offer entry opportunities within a trend.',
        ['Impulses are strong, fast moves.', 'Corrections are shallower pullbacks.', 'Trade impulses, be cautious in corrections.'],
        'In an uptrend, a strong push up (impulse) is followed by a slow drift down (correction) to support.',
        { q: 'In an uptrend, a correction is a:', options: ['Strong push up', 'Counter-trend pullback', 'New low', 'Doji'], correct: 1, explain: 'Corrections are counter-trend pullbacks within the trend.' }),
      L('pa-8', 'Consolidation & Range',
        'Consolidation is price moving sideways between support and resistance with no clear trend. It represents balance. Breakouts from consolidation can be powerful, but many fail — wait for confirmation.',
        ['Range = price balanced between levels.', 'Volume often drops in ranges.', 'Trade the edges until a confirmed breakout.'],
        'A stock bounces between 100 and 110 for three weeks — a range. Traders buy 100, sell 110.',
        { q: 'A range is best described as:', options: ['A strong trend', 'Sideways balance between levels', 'A reversal pattern', 'A gap'], correct: 1, explain: 'A range is sideways price action between support and resistance.' }),
      L('pa-9', 'Momentum',
        'Momentum is the speed and strength of price movement. Strong momentum (large candles, little pullback) suggests conviction. Fading momentum can warn of exhaustion but is not a guaranteed reversal.',
        ['Large candles = strong momentum.', 'Momentum fades before price reverses sometimes.', 'Use momentum to gauge conviction, not to predict tops.'],
        'A stock rallies with 5 large green candles and no pullback — strong bullish momentum.',
        { q: 'Strong momentum is shown by:', options: ['Small dojis', 'Large directional candles', 'Flat volume', 'A range'], correct: 1, explain: 'Large directional candles indicate strong momentum.' }),
      L('pa-10', 'Rejection',
        'Rejection is price pushing into a level and then sharply reversing away from it, often leaving a long wick. It shows the level held and participants defended it. Rejections at key levels are meaningful.',
        ['Long wick at a level = rejection.', 'Shows defense of the level.', 'Stronger with confluence.'],
        'Price spikes up to resistance at 120 and closes back at 114 with a long upper wick — rejection of resistance.',
        { q: 'A long upper wick at resistance suggests:', options: ['Buyers won', 'Rejection of higher prices', 'A breakout', 'A doji'], correct: 1, explain: 'A long upper wick at resistance shows rejection of higher prices.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 4 — SUPPORT & RESISTANCE
  // ─────────────────────────────────────────────
  {
    id: 'support-resistance',
    title: 'Support & Resistance',
    icon: '📐',
    color: 'purple',
    description: 'The levels where price reacts. Learn to map them, trade them, and spot when they break.',
    lessons: [
      L('sr-1', 'What is Support?',
        'Support is a price level where buying interest is strong enough to overcome selling, causing price to stop falling and bounce. It is not a floor — it can break.',
        ['Support = demand overwhelms supply.', 'Multiple touches strengthen it.', 'Breaking support often leads to further falls.'],
        'A stock falls to 100 three times and bounces — 100 is a strong support level.',
        { q: 'Support is a level where:', options: ['Sellers dominate', 'Buying overcomes selling', 'Price always rises', 'Volume is zero'], correct: 1, explain: 'Support is where buying demand overcomes selling.' }),
      L('sr-2', 'What is Resistance?',
        'Resistance is a price level where selling overcomes buying, causing price to stop rising and fall. It acts as a ceiling until broken.',
        ['Resistance = supply overwhelms demand.', 'Multiple touches strengthen it.', 'Breaking resistance often leads to further rises.'],
        'A stock rises to 120 three times and falls — 120 is resistance.',
        { q: 'Resistance acts as a:', options: ['Floor', 'Ceiling', 'Trend line', 'Volume bar'], correct: 1, explain: 'Resistance acts as a ceiling where selling overcomes buying.' }),
      L('sr-3', 'Strong vs Weak Levels',
        'A strong level has multiple touches, clear reactions, and is visible on higher timeframes. A weak level has one touch or minor reactions. Strong levels are more reliable for entries and targets.',
        ['Multiple touches + clear reactions = strong.', 'Higher timeframe levels are stronger.', 'Weak levels break easily.'],
        'A daily support tested 4 times with sharp bounces is stronger than a 15m level touched once.',
        { q: 'Which level is likely strongest?', options: ['A 15m level touched once', 'A daily level tested 4 times', 'A random round number', 'A level with no reactions'], correct: 1, explain: 'Higher-timeframe levels with multiple tests are strongest.' }),
      L('sr-4', 'Support Becoming Resistance (and vice versa)',
        'When a support level breaks, it often becomes resistance on the way back up. When resistance breaks, it often becomes support on the way back down. This is called role reversal.',
        ['Broken support → new resistance.', 'Broken resistance → new support.', 'Role reversal is a core concept.'],
        'Price breaks support at 100, falls, then rallies back to 100 and stalls — old support is now resistance.',
        { q: 'After resistance is broken, it often becomes:', options: ['Stronger resistance', 'New support', 'Irrelevant', 'A doji'], correct: 1, explain: 'Broken resistance often becomes new support (role reversal).' }),
      L('sr-5', 'False Breakouts',
        'A false breakout is when price briefly moves beyond a level then reverses back. It traps traders who entered on the breakout. Confirmation (close beyond level, retest) reduces false-breakout risk.',
        ['Brief break + reversal = false breakout.', 'Traps breakout traders.', 'Wait for a confirmed close.'],
        'Price spikes above resistance to 122 then closes back below 120 — a false breakout.',
        { q: 'A false breakout is best avoided by:', options: ['Entering on the wick immediately', 'Waiting for a confirmed close beyond the level', 'Using maximum leverage', 'Ignoring the level'], correct: 1, explain: 'A confirmed close beyond the level reduces false-breakout risk.' }),
      L('sr-6', 'Confluence',
        'Confluence is when multiple factors align at one level — e.g. a support level that also matches a moving average, a Fibonacci level, and a prior breakout point. Confluence increases the significance of a level.',
        ['More factors at one level = stronger.', 'Confluence improves risk/reward.', 'Still not guaranteed — manage risk.'],
        'A support at 100 also matches the 200 EMA and a 61.8% Fibonacci retracement — high confluence.',
        { q: 'Confluence means:', options: ['One factor at a level', 'Multiple factors aligning at one level', 'No factors', 'Random entry'], correct: 1, explain: 'Confluence is multiple independent factors aligning at one level.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 5 — SUPPLY & DEMAND
  // ─────────────────────────────────────────────
  {
    id: 'supply-demand',
    title: 'Supply & Demand',
    icon: '💧',
    color: 'blue',
    description: 'Understand where institutional orders cluster and how price reacts to these zones.',
    lessons: [
      L('sd-1', 'Supply & Demand Basics',
        'Demand is where buyers are concentrated (price rises from there). Supply is where sellers are concentrated (price falls from there). Price moves between these zones seeking balance.',
        ['Demand zone = strong buying.', 'Supply zone = strong selling.', 'Price reacts when returning to zones.'],
        'Price rockets up from 100, leaving a demand zone at 100 where buyers were waiting.',
        { q: 'A demand zone is where:', options: ['Sellers dominate', 'Buyers are concentrated', 'Price is flat', 'Volume is zero'], correct: 1, explain: 'Demand zones are where buyers concentrate and push price up.' }),
      L('sd-2', 'Fresh vs Touched Zones',
        'A fresh zone has not been tested since it formed — it may react strongly. A zone that has been tested multiple times is weaker, as orders there have been filled.',
        ['Fresh zones react strongest.', 'Multiple touches weaken a zone.', 'First return is the highest-probability.'],
        'A demand zone at 100 is touched once and bounces sharply; a third touch may fail.',
        { q: 'Which zone is likely strongest?', options: ['A zone touched 4 times', 'A fresh, untested zone', 'A zone with no reaction', 'A round number only'], correct: 1, explain: 'Fresh, untested zones tend to react most strongly.' }),
      L('sd-3', 'Strong vs Weak Zones',
        'Strong zones form after explosive moves (imbalance) leaving little trading in between. Weak zones form after slow, choppy moves. The strength of the move away indicates the order strength.',
        ['Explosive move away = strong zone.', 'Choppy move away = weak zone.', 'Use the move away to gauge strength.'],
        'A demand zone where price shot up 8% in one candle is stronger than one where price drifted up slowly.',
        { q: 'A strong demand zone typically has:', options: ['A slow move away', 'An explosive move away', 'No move', 'A doji'], correct: 1, explain: 'Explosive moves away indicate strong unmet orders at the zone.' }),
      L('sd-4', 'Combining Supply/Demand with Price Action',
        'Supply/demand zones are most useful when combined with price action: a demand zone that aligns with a higher-timeframe support and shows a bullish rejection is a higher-probability setup than either alone.',
        ['Confluence raises probability.', 'Wait for confirmation at the zone.', 'Still manage risk — no guarantee.'],
        'Price returns to a demand zone that also aligns with a trend support and prints a hammer — a confluence entry.',
        { q: 'Supply/demand zones work best:', options: ['In isolation', 'Combined with price action and structure', 'With maximum leverage', 'Without stop losses'], correct: 1, explain: 'Combining zones with price action and structure raises probability.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 6 — MARKET STRUCTURE & TOP-DOWN ANALYSIS
  // ─────────────────────────────────────────────
  {
    id: 'market-structure',
    title: 'Market Structure & Top-Down',
    icon: '📊',
    color: 'green',
    description: 'Analyze multiple timeframes from the top down to build a structured, objective market view.',
    lessons: [
      L('ms-1', 'Multi-Timeframe Analysis',
        'Top-down analysis means starting at a high timeframe (monthly/weekly) for the big trend, then drilling to lower timeframes (4H, 1H, 15M) for entries. This aligns trades with the dominant trend.',
        ['High timeframe = context and trend.', 'Low timeframe = precise entry.', 'Alignment across timeframes = higher probability.'],
        'Weekly is bullish, daily is bullish, 1H shows a pullback to support — a top-down long setup.',
        { q: 'Top-down analysis starts at the:', options: ['15M chart', 'Highest timeframe', '1M chart', 'Tick chart'], correct: 1, explain: 'Top-down analysis begins at the highest timeframe for context.' }),
      L('ms-2', 'Trend Alignment',
        'When higher and lower timeframes agree on direction, trades have higher probability. When they conflict, the lower timeframe is trading against the dominant trend — higher risk.',
        ['Aligned timeframes = higher probability.', 'Conflicting timeframes = higher risk.', 'Trade with the dominant trend.'],
        'Daily uptrend + 1H uptrend = aligned longs are favored. Daily up + 1H down = counter-trend, risky.',
        { q: 'When timeframes conflict, you should:', options: ['Use maximum leverage', 'Be cautious — higher risk', 'Ignore the higher timeframe', 'Always short'], correct: 1, explain: 'Conflicting timeframes mean higher risk; trade with caution.' }),
      L('ms-3', 'Higher & Lower Timeframe Structure',
        'Higher timeframe (HTF) structure defines the major trend and key levels. Lower timeframe (LTF) structure gives precise entries and early reversal signals (CHoCH). Combine both for context + entry.',
        ['HTF = major levels and trend.', 'LTF = entry precision and early shifts.', 'Use LTF CHoCH for early entry within HTF trend.'],
        'HTF shows support at 100; LTF shows a CHoCH up at 100 — an early long entry within the HTF trend.',
        { q: 'Lower timeframe structure provides:', options: ['Major trend only', 'Precise entries and early shifts', 'No useful info', 'Guaranteed profit'], correct: 1, explain: 'LTF structure gives precise entries and early reversal signals.' }),
      L('ms-4', 'Building a Structured Analysis',
        'A structured analysis: identify HTF trend → mark HTF key levels → find LTF structure at those levels → plan entry, stop, and target → define invalidation. This replaces guessing with a plan.',
        ['Step-by-step, not guessing.', 'Always define invalidation.', 'Plan entry, stop, and target before entering.'],
        'Weekly up → daily support at 100 → 1H CHoCH up at 100 → enter 101, stop 98, target 115.',
        { q: 'A structured analysis always defines:', options: ['Guaranteed profit', 'Invalidation (stop)', 'Maximum leverage', 'No stop loss'], correct: 1, explain: 'A structured plan always defines where the idea is wrong (invalidation).' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 7 — TECHNICAL ANALYSIS
  // ─────────────────────────────────────────────
  {
    id: 'technical-analysis',
    title: 'Technical Analysis',
    icon: '📊',
    color: 'blue',
    description: 'Indicators as supporting tools — never as guaranteed buy/sell signals.',
    lessons: [
      L('ta-1', 'Moving Averages (SMA & EMA)',
        'A Simple Moving Average (SMA) averages price over N periods equally. An Exponential Moving Average (EMA) weights recent prices more. They help identify trend and act as dynamic support/resistance. They lag, so they confirm — they do not predict.',
        ['SMA = equal weight; EMA = recent-weighted.', 'Price above a rising MA = uptrend bias.', 'MAs lag — they confirm, not predict.'],
        'Price stays above a rising 50 EMA for weeks — a clear uptrend using the EMA as dynamic support.',
        { q: 'A key limitation of moving averages is:', options: ['They predict tops perfectly', 'They lag price', 'They never fail', 'They are leading indicators'], correct: 1, explain: 'Moving averages lag price; they confirm, not predict.' }),
      L('ta-2', 'RSI (Relative Strength Index)',
        'RSI measures momentum from 0–100. Traditionally above 70 = overbought, below 30 = oversold. But overbought does not mean "sell" — strong trends can stay overbought for long periods. Divergence (price up, RSI down) can warn of fading momentum.',
        ['Overbought ≠ automatic sell.', 'Oversold ≠ automatic buy.', 'Divergence warns of momentum shifts.'],
        'A stock in a strong uptrend keeps RSI above 70 for weeks — selling just because RSI > 70 would miss the trend.',
        { q: 'RSI above 70 means:', options: ['Guaranteed sell', 'Overbought — but may stay so in a trend', 'Certain crash', 'Buy signal'], correct: 1, explain: 'Overbought RSI does not guarantee a drop in strong trends.' }),
      L('ta-3', 'MACD',
        'MACD shows the relationship between two EMAs. It has a MACD line, a signal line, and a histogram. Crossovers of the lines and histogram momentum shifts are used to gauge trend strength and turns. Like all indicators, it lags.',
        ['MACD line crosses signal = momentum shift.', 'Histogram shows momentum strength.', 'Divergence can warn of weakness.'],
        'MACD line crosses above the signal line while the histogram turns positive — bullish momentum shift.',
        { q: 'MACD is primarily a:', options: ['Leading predictor', 'Momentum/trend indicator that lags', 'Volume tool', 'Fundamental tool'], correct: 1, explain: 'MACD is a momentum indicator based on EMAs; it lags.' }),
      L('ta-4', 'Bollinger Bands',
        'Bollinger Bands are a moving average with upper and lower bands based on standard deviation. They expand with volatility and contract during squeezes. Price touching a band is not a buy/sell signal on its own.',
        ['Bands widen with volatility.', 'Squeeze = low volatility, often precedes expansion.', 'Bands are not automatic reversal signals.'],
        'Bands squeeze tightly for days, then price breaks out with expanding bands — volatility expansion.',
        { q: 'A Bollinger Band squeeze indicates:', options: ['Guaranteed breakout direction', 'Low volatility, possible expansion ahead', 'A sell signal', 'A doji'], correct: 1, explain: 'A squeeze means low volatility that often precedes expansion — direction not guaranteed.' }),
      L('ta-5', 'VWAP',
        'VWAP (Volume Weighted Average Price) is the average price weighted by volume, used intraday. Price above VWAP suggests bullish intraday bias; below suggests bearish. It is reset each day and mainly useful for day trading.',
        ['VWAP is intraday only.', 'Price above VWAP = bullish bias.', 'Often acts as intraday support/resistance.'],
        'A stock opens, dips to VWAP, bounces — VWAP acting as intraday support.',
        { q: 'VWAP is most useful for:', options: ['Long-term investing', 'Intraday trading', 'Monthly charts', 'Fundamental analysis'], correct: 1, explain: 'VWAP is an intraday benchmark, reset daily.' }),
      L('ta-6', 'Fibonacci Retracement',
        'Fibonacci retracements (38.2%, 50%, 61.8%) mark potential pullback zones in a trend. They work best with confluence (structure, support/resistance). They are not magic levels and do not guarantee a bounce.',
        ['Common levels: 38.2%, 50%, 61.8%.', 'Best used with confluence.', 'Not guaranteed reversal points.'],
        'In an uptrend, price pulls back to the 61.8% Fib that aligns with prior support — a confluence zone.',
        { q: 'Fibonacci retracements are best used:', options: ['Alone, as guaranteed levels', 'With confluence', 'On 1M charts only', 'Without stops'], correct: 1, explain: 'Fib levels are strongest when combined with other confluence factors.' }),
      L('ta-7', 'Volume',
        'Volume measures the number of units traded. High volume confirms moves; low volume questions them. Volume spikes on breakouts add conviction; volume divergence (price up, volume falling) can warn of weakness.',
        ['High volume = conviction.', 'Breakout on low volume = suspect.', 'Volume confirms, not predicts.'],
        'A resistance breakout on 3x average volume is more trustworthy than one on half average volume.',
        { q: 'A breakout on low volume is:', options: ['Highly reliable', 'Suspect — may fail', 'A guaranteed win', 'Irrelevant'], correct: 1, explain: 'Low-volume breakouts lack conviction and often fail.' }),
      L('ta-8', 'ATR (Volatility & Stops)',
        'ATR (Average True Range) measures average price range per candle. It helps set stop losses sized to current volatility — wider in volatile markets, tighter in calm ones. It does not predict direction.',
        ['ATR = average range per period.', 'Use ATR to size stops to volatility.', 'Higher ATR = wider stops needed.'],
        'With ATR of $2, a trader sets a stop 1.5x ATR ($3) away to avoid noise.',
        { q: 'ATR is mainly used to:', options: ['Predict direction', 'Size stops to volatility', 'Guarantee profit', 'Replace price action'], correct: 1, explain: 'ATR helps size stops according to current volatility.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 8 — CHART READING
  // ─────────────────────────────────────────────
  {
    id: 'chart-reading',
    title: 'Chart Reading',
    icon: '📖',
    color: 'amber',
    description: 'Put it all together — read a chart like a story: trend, levels, momentum, and context.',
    lessons: [
      L('cr-1', 'Timeframes & Context',
        'Each timeframe tells a different story. The higher timeframe gives the dominant context; the lower timeframe gives detail. Always know which timeframe you are trading and what the higher one is doing.',
        ['Higher TF = context.', 'Lower TF = detail/entry.', 'Never trade a lower TF against the higher TF blindly.'],
        'A 15M breakout long fails because the daily chart is in a downtrend — context was ignored.',
        { q: 'Which timeframe gives the dominant context?', options: ['1M', 'The highest relevant timeframe', 'Tick', '5S'], correct: 1, explain: 'Higher timeframes give the dominant context.' }),
      L('cr-2', 'Reading a Chart Step-by-Step',
        'A structured read: 1) Identify trend (HH/HL or LH/LL). 2) Mark key support/resistance. 3) Note momentum and volume. 4) Find the current location relative to levels. 5) Plan only then.',
        ['Trend first, then levels.', 'Momentum and volume next.', 'Plan last, not first.'],
        'A trader opens a chart, sees an uptrend, marks support at 100, notes strong volume, then plans a long at 100.',
        { q: 'The first step in reading a chart is:', options: ['Place an order', 'Identify the trend', 'Check RSI only', 'Set leverage'], correct: 1, explain: 'Identifying trend is the first step in structured chart reading.' }),
      L('cr-3', 'Location Matters',
        'The same candle means different things in different locations. A hammer at support is a potential reversal; the same hammer mid-range means little. Always ask "where is this happening?"',
        ['Context > pattern.', 'Location changes meaning.', 'Never trade a pattern in isolation.'],
        'A bullish engulfing at support is meaningful; the same engulfing in the middle of a range is not.',
        { q: 'A candle pattern meaning depends most on:', options: ['Its color only', 'Its location/context', 'The time of day', 'The symbol only'], correct: 1, explain: 'Context and location determine a pattern meaning.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 9 — TRADING STRATEGIES
  // ─────────────────────────────────────────────
  {
    id: 'strategies',
    title: 'Trading Strategies',
    icon: '🎯',
    color: 'purple',
    description: 'Strategy concepts with setups, entries, invalidation, and when NOT to use them. Never guaranteed profitable.',
    lessons: [
      L('strat-1', 'Trend Following',
        'Buy in an established uptrend (HH/HL) on pullbacks to support or a moving average. Entry on confirmation the pullback is over; stop below the last HL; target the next swing high or beyond. Fails in ranges.',
        ['Trade with the trend.', 'Enter on pullbacks, not chasing.', 'Invalidation: break of the last HL.'],
        'In an uptrend, buy a pullback to the 50 EMA that holds; stop below the HL; target new highs.',
        { q: 'Trend following works best in:', options: ['A range', 'A clear trending market', 'A crash only', 'Low liquidity'], correct: 1, explain: 'Trend following needs a clear trend; it struggles in ranges.' }),
      L('strat-2', 'Breakout + Retest',
        'Wait for price to break a key level, then enter on the retest of the broken level (now support/resistance). This avoids many false breakouts and offers a tight stop. Fails when the retest does not hold.',
        ['Break first, then retest.', 'Enter on confirmation at retest.', 'Invalidation: retest fails (level breaks back).'],
        'Price breaks resistance at 100, pulls back to 100, holds, and resumes up — enter at 101, stop 98.',
        { q: 'The breakout+retest entry happens:', options: ['During the breakout spike', 'On the retest of the broken level', 'Before the breakout', 'Randomly'], correct: 1, explain: 'The entry is on the retest, which confirms the level held.' }),
      L('strat-3', 'Pullback (Trend Continuation)',
        'In a trend, wait for a shallow counter-trend pullback, then enter in the trend direction once the pullback shows it is ending (e.g. a CHoCH on the lower timeframe). Stop beyond the pullback extreme.',
        ['Enter in trend direction after a pullback.', 'Pullback should be shallow.', 'Invalidation: pullback becomes a reversal.'],
        'In an uptrend, price pulls back to a small support, prints a bullish CHoCH on 1H — enter long.',
        { q: 'A pullback entry is a:', options: ['Counter-trend trade', 'Trend-continuation entry', 'Range trade', 'Scalp only'], correct: 1, explain: 'Pullback entries trade in the trend direction after a counter-trend dip.' }),
      L('strat-4', 'Range Trading',
        'In a clear range, buy at support and sell at resistance, until a confirmed breakout. Stops go just beyond the range edge. Fails when the range breaks — so always use a stop.',
        ['Buy support, sell resistance.', 'Stops just beyond the range.', 'Exit on a confirmed breakout.'],
        'A stock ranges 100–110; buy 100, sell 110, stop 97, repeat until breakout.',
        { q: 'Range trading fails when:', options: ['The range continues', 'The range breaks out', 'Volume drops', 'Price stays flat'], correct: 1, explain: 'Range trading fails when the range breaks; stops protect you.' }),
      L('strat-5', 'When NOT to Trade a Strategy',
        'Every strategy has conditions where it fails: trend strategies in ranges, range strategies in breakouts, breakout strategies in low volatility. Knowing when NOT to trade is as important as knowing when to trade.',
        ['Match strategy to market condition.', 'No strategy works in all conditions.', 'Skipping is a valid decision.'],
        'A trend-following trader sees a tight range and stands aside — correct decision.',
        { q: 'A trend strategy should be avoided in:', options: ['A strong trend', 'A tight sideways range', 'High liquidity', 'A breakout'], correct: 1, explain: 'Trend strategies struggle in sideways ranges.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 10 — RISK MANAGEMENT
  // ─────────────────────────────────────────────
  {
    id: 'risk-management',
    title: 'Risk Management',
    icon: '🛡️',
    color: 'red',
    description: 'The most important course. Protect capital first; profits come second.',
    lessons: [
      L('rm-1', 'Why Risk Management Matters',
        'You cannot control the market, only how much you risk. A single bad trade without risk control can wipe out months of gains. Risk management keeps you in the game long enough for your edge to work.',
        ['You control risk, not the market.', 'One bad unmanaged trade can be catastrophic.', 'Survival > short-term profit.'],
        'A trader risking 50% per trade loses 90% of capital after a few losses; risking 1% survives long streaks.',
        { q: 'The main purpose of risk management is:', options: ['To guarantee profit', 'To protect capital and stay in the game', 'To increase leverage', 'To remove stops'], correct: 1, explain: 'Risk management protects capital so you survive to let your edge work.' }),
      L('rm-2', 'Risk Per Trade',
        'Risk per trade is the percentage of capital you are willing to lose on a single trade if your stop is hit. Professional traders often risk 0.5–2% per trade. This makes a losing streak survivable.',
        ['Common risk: 0.5–2% per trade.', 'Keeps losing streaks survivable.', 'Risk % is based on stop distance × size.'],
        'On ₹100,000 capital risking 1%, the maximum loss per trade is ₹1,000.',
        { q: 'A common professional risk per trade is:', options: ['50%', '10%', '0.5–2%', '100%'], correct: 2, explain: '0.5–2% per trade keeps losing streaks survivable.' }),
      L('rm-3', 'Position Sizing',
        'Position size = (Capital × Risk%) / (Entry − Stop). This ensures you lose only your planned risk if the stop is hit. Larger stop = smaller size; smaller stop = larger size, for the same risk.',
        ['Size = (Capital × Risk%) / Stop distance.', 'Same risk, different sizes for different stops.', 'Never size by "feeling" — calculate it.'],
        'Capital ₹100,000, risk 1% (₹1,000), entry 100, stop 98 → size = 1000 / 2 = 500 shares.',
        { q: 'If your stop distance doubles, position size should:', options: ['Double', 'Halve', 'Stay the same', 'Triple'], correct: 1, explain: 'For the same risk, a wider stop means a smaller position size.' }),
      L('rm-4', 'Risk/Reward Ratio',
        'Risk/reward (R:R) compares potential loss to potential gain. A 1:2 R:R means you risk 1 to make 2. With 1:2, you can be wrong more than half the time and still be profitable.',
        ['R:R = reward / risk.', '1:2 lets you lose over half your trades and still profit.', 'Always plan R:R before entering.'],
        'Risk ₹1,000 to make ₹2,000 = 1:2. Win 40% of trades → still profitable.',
        { q: 'A 1:2 risk/reward means:', options: ['Risk 2 to make 1', 'Risk 1 to make 2', 'No stop loss', 'Guaranteed win'], correct: 1, explain: '1:2 means risking 1 unit to make 2 units.' }),
      L('rm-5', 'Stop Loss & Take Profit',
        'A stop loss is where your idea is proven wrong — always define it before entering. A take profit is your planned exit for a win. Moving a stop wider to avoid being stopped out is a classic account-killer.',
        ['Always predefine your stop.', 'Take profit plans your exit.', 'Never widen a stop to "hope" price returns.'],
        'A trader enters at 100, stop 98, target 106. Price hits 98 — they exit, accepting the small planned loss.',
        { q: 'Widening your stop loss when price approaches it is:', options: ['Good practice', 'A dangerous habit that blows up accounts', 'Required', 'A strategy'], correct: 1, explain: 'Widening stops to avoid being stopped out is a classic account-killer.' }),
      L('rm-6', 'Maximum Drawdown & Losing Streaks',
        'Drawdown is the drop from your account peak. Losing streaks are statistically normal even with a good strategy. Risking a small % per trade keeps drawdowns shallow enough to recover from.',
        ['Drawdowns are inevitable.', 'Small risk % keeps them recoverable.', 'A 50% drawdown needs a 100% gain to recover.'],
        'A 50% drawdown requires a 100% gain just to break even — far harder than avoiding it.',
        { q: 'A 50% drawdown requires a ___ gain to recover.', options: ['25%', '50%', '100%', '10%'], correct: 2, explain: 'Recovering a 50% drawdown requires a 100% gain — asymmetry of drawdowns.' }),
      L('rm-7', 'Overtrading & Revenge Trading',
        'Overtrading is taking too many trades, often out of boredom or frustration. Revenge trading is increasing risk to "win back" a loss. Both are emotional and destroy accounts. A trading plan with rules prevents both.',
        ['Overtrading = too many trades.', 'Revenge trading = chasing losses with bigger risk.', 'A plan prevents both.'],
        'After two losses, a trader doubles position size to "win it back" — revenge trading, soon wiped out.',
        { q: 'Revenge trading is:', options: ['Increasing risk to recover a loss', 'Following your plan', 'A long-term strategy', 'Risk-free'], correct: 0, explain: 'Revenge trading is chasing losses with larger risk — destructive.' }),
      L('rm-8', 'Building a Trading Plan',
        'A trading plan defines your setups, timeframes, risk per trade, max daily loss, and rules for entering and exiting. Trading without a plan is gambling. Review and refine the plan regularly using your journal.',
        ['Define setups, risk, and rules.', 'A plan removes emotion.', 'Review it with your journal.'],
        'A plan: "I trade trend pullbacks on 1H, risk 1%, max 3 trades/day, stop loss always, no trading after 2 losses."',
        { q: 'A trading plan mainly helps you:', options: ['Guarantee profit', 'Remove emotion and stay disciplined', 'Avoid all losses', 'Use more leverage'], correct: 1, explain: 'A plan removes emotion and enforces discipline.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 11 — TRADING PSYCHOLOGY
  // ─────────────────────────────────────────────
  {
    id: 'psychology',
    title: 'Trading Psychology',
    icon: '🧠',
    color: 'purple',
    description: 'Master the mind. Discipline, emotion control, and consistency beat any single strategy.',
    lessons: [
      L('psy-1', 'Fear & Greed',
        'Fear makes you cut winners too early and avoid valid trades. Greed makes you overtrade and hold losers hoping for more. Awareness of these emotions is the first step to managing them.',
        ['Fear shrinks winners.', 'Greed grows losers.', 'Awareness precedes control.'],
        'A trader holds a losing position hoping it "comes back" — greed and hope, not a plan.',
        { q: 'Greed often causes traders to:', options: ['Cut winners early', 'Hold losers too long hoping for more', 'Use tight stops', 'Avoid trading'], correct: 1, explain: 'Greed leads to holding losers and overtrading.' }),
      L('psy-2', 'FOMO',
        'FOMO (Fear Of Missing Out) makes you chase moves after they have already happened, entering at bad prices with bad risk/reward. The move you missed is gone — wait for the next setup.',
        ['FOMO = chasing missed moves.', 'Leads to bad entries and R:R.', 'Wait for the next setup.'],
        'A stock already up 10%, a trader buys at the top out of FOMO — it reverses immediately.',
        { q: 'FOMO typically results in:', options: ['A well-planned entry', 'Chasing a move at a bad price', 'A long-term hold', 'A stop loss'], correct: 1, explain: 'FOMO causes chasing moves at poor entry prices.' }),
      L('psy-3', 'Revenge Trading',
        'After a loss, the urge to "win it back" immediately by increasing size is revenge trading. It is emotional, not planned, and is one of the fastest ways to blow up an account. Step away after losses instead.',
        ['Revenge trading = emotional, bigger risk.', 'Step away after losses.', 'Stick to your plan size.'],
        'After a stop-out, a trader doubles size on the next trade "to recover" — revenge trading.',
        { q: 'After a loss, the best action is usually to:', options: ['Double position size', 'Follow your plan and risk rules', 'Remove your stop loss', 'Trade more aggressively'], correct: 1, explain: 'Following your plan and risk rules after a loss prevents revenge trading.' }),
      L('psy-4', 'Accepting Losses',
        'Losses are a normal part of trading, not a personal failure. A good trader accepts small planned losses calmly. Denying losses (holding, widening stops) turns small losses into large ones.',
        ['Losses are inevitable and normal.', 'Accept them calmly and small.', 'Denial makes them bigger.'],
        'A trader takes a planned ₹500 loss and moves on — a sign of discipline, not failure.',
        { q: 'A professional trader views small losses as:', options: ['A personal failure', 'A normal part of the process', 'A reason to quit', 'A reason to revenge trade'], correct: 1, explain: 'Small planned losses are a normal, accepted part of trading.' }),
      L('psy-5', 'Consistency Over Perfection',
        'Consistency — following your plan every time — beats trying to be perfect. You will have losses; the goal is a repeatable process with positive expectancy, not a perfect win rate.',
        ['Process over perfection.', 'Consistency builds positive expectancy.', 'You will lose sometimes — that is fine.'],
        'A trader with a 55% win rate and 1:2 R:R is profitable over time through consistency.',
        { q: 'The key to long-term success is:', options: ['A 100% win rate', 'A consistent, repeatable process', 'Never losing', 'Maximum leverage'], correct: 1, explain: 'Consistency and process beat chasing a perfect win rate.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 12 — TRADING JOURNAL
  // ─────────────────────────────────────────────
  {
    id: 'journal',
    title: 'Trading Journal',
    icon: '📓',
    color: 'amber',
    description: 'Record, review, and improve. The journal is how you turn experience into edge.',
    lessons: [
      L('jr-1', 'Why Keep a Journal',
        'A journal turns each trade into data. Over time it reveals which setups work for you, which mistakes repeat, and where your edge is. Without a journal, you repeat the same errors blindly.',
        ['A journal = feedback loop.', 'Reveals your real edge and mistakes.', 'No journal = no improvement.'],
        'A trader reviews 50 journal entries and finds 80% of losses come from one mistake: entering before confirmation.',
        { q: 'The main purpose of a journal is:', options: ['To look professional', 'To create a feedback loop for improvement', 'To guarantee profit', 'To replace a plan'], correct: 1, explain: 'A journal creates a feedback loop that drives improvement.' }),
      L('jr-2', 'What to Record',
        'Record the facts (symbol, direction, entry, exit, stop, target, size, result) AND the context (setup, strategy, screenshot, notes, emotions, mistakes). Facts let you analyze; context lets you learn.',
        ['Facts: prices, size, result.', 'Context: setup, emotions, mistakes.', 'A screenshot is worth a thousand words.'],
        'A journal entry: "Long AAPL, entry 220, stop 217, target 230, setup: trend pullback, emotion: calm, mistake: none."',
        { q: 'Besides prices and result, you should also record:', options: ['Nothing', 'Setup, emotions, and mistakes', 'Only the date', 'Only the symbol'], correct: 1, explain: 'Context — setup, emotions, mistakes — is what you learn from.' }),
      L('jr-3', 'Reviewing Your Journal',
        'Review weekly: win rate, average win, average loss, R:R, best and worst setups, recurring mistakes. Patterns emerge over 20+ trades. Use the review to refine your plan and drop what does not work.',
        ['Review weekly.', 'Look for patterns over 20+ trades.', 'Refine your plan from findings.'],
        'A weekly review shows your win rate is 60% with trend setups but 30% with range setups — drop range setups.',
        { q: 'A journal review should look for:', options: ['Random noise', 'Patterns in your setups and mistakes', 'Only your best trade', 'Nothing'], correct: 1, explain: 'Reviews reveal patterns in setups and mistakes to refine your plan.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 13 — HISTORICAL PRACTICE
  // ─────────────────────────────────────────────
  {
    id: 'historical-practice',
    title: 'Historical Practice',
    icon: '🎮',
    color: 'green',
    description: 'Practice on REAL historical data. Clearly labeled — this is NOT live trading.',
    lessons: [
      L('hp-1', 'What is Historical Practice?',
        'Historical practice loads real past market data, hides the future, lets you analyze the visible chart and form a plan, then reveals what actually happened. It builds pattern recognition without risking capital. It is practice, not live trading.',
        ['Uses real past data.', 'Future is hidden until you commit.', 'Educational — not live trading.'],
        'You load BTC daily data up to a hidden point, analyze, predict, then reveal the real subsequent candles.',
        { q: 'Historical practice uses:', options: ['Fake data', 'Real past market data', 'Random candles', 'Guaranteed setups'], correct: 1, explain: 'Historical practice uses real past data, with the future hidden.' }),
      L('hp-2', 'How to Practice Effectively',
        'Form a complete plan before revealing: trend, levels, setup, entry, stop, target, and invalidation. Then reveal and judge your process — not just whether price went up or down. Good process with a loss beats lucky wins.',
        ['Plan fully before revealing.', 'Judge process, not just outcome.', 'Good process > lucky wins.'],
        'You plan a long at support with a stop, reveal shows price hit your stop first — but your process was sound.',
        { q: 'In historical practice, you should judge:', options: ['Only if price went your way', 'Your process and plan quality', 'Only your profit', 'Your speed'], correct: 1, explain: 'Judge the quality of your process, not just the outcome.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 14 — PAPER TRADING
  // ─────────────────────────────────────────────
  {
    id: 'paper-trading',
    title: 'Paper Trading',
    icon: '🧪',
    color: 'amber',
    description: 'Virtual money, real practice. Clearly labeled — never real-money trading.',
    lessons: [
      L('pt-1', 'What is Paper Trading?',
        'Paper trading simulates trades with virtual money using live or simulated prices. It lets you practice execution and test strategies risk-free. It is virtual money — never real money. Emotionally, it differs from real trading.',
        ['Virtual money only.', 'Practice execution risk-free.', 'Emotionally easier than real trading.'],
        'You paper-trade a breakout strategy for a month with ₹100,000 virtual — no real money at risk.',
        { q: 'Paper trading uses:', options: ['Real money', 'Virtual money', 'Borrowed money', 'No prices'], correct: 1, explain: 'Paper trading uses virtual money — never real money.' }),
      L('pt-2', 'Limits of Paper Trading',
        'Paper trading does not replicate the emotions of real money, slippage, or execution pressure. Use it to learn mechanics and test logic, then transition carefully to small real risk. Success in paper does not guarantee real success.',
        ['No real emotion.', 'May ignore slippage.', 'Paper success ≠ real success.'],
        'A trader is profitable on paper but loses with real money due to emotion and slippage.',
        { q: 'A key limit of paper trading is:', options: ['It uses real money', 'It lacks real-money emotion', 'It is illegal', 'It guarantees profit'], correct: 1, explain: 'Paper trading does not replicate the emotion of real money.' }),
    ],
  },

  // ─────────────────────────────────────────────
  // COURSE 15 — ADVANCED MARKET CONCEPTS
  // ─────────────────────────────────────────────
  {
    id: 'advanced',
    title: 'Advanced Market Concepts',
    icon: '🔬',
    color: 'blue',
    description: 'Liquidity, imbalances, order blocks, Wyckoff — distinguish established concepts from trader frameworks.',
    lessons: [
      L('adv-1', 'Liquidity & Liquidity Sweeps',
        'Liquidity refers to the orders resting above/below key levels. A liquidity sweep (or stop hunt) is when price spikes beyond a level to trigger those orders, then reverses. It is a market concept, not a guaranteed pattern — and interpretations vary.',
        ['Liquidity = resting orders at levels.', 'Sweeps trigger then reverse.', 'Interpretations vary — not guaranteed.'],
        'Price spikes just above resistance, triggers breakout buy stops, then drops back — a liquidity sweep.',
        { q: 'A liquidity sweep is when price:', options: ['Stays flat', 'Spikes beyond a level to trigger orders then reverses', 'Goes straight up forever', 'Forms a doji'], correct: 1, explain: 'A sweep spikes beyond a level to trigger resting orders, then reverses.' }),
      L('adv-2', 'Imbalances & Fair Value Gaps',
        'An imbalance (Fair Value Gap) is a gap left by a fast move where little trading occurred — price may return to "fill" it. It is a trader framework, not a law. Treat it as a possible reaction zone, not a guarantee.',
        ['FVG = gap from a fast move.', 'Price may return to fill it.', 'A framework, not a guarantee.'],
        'A 3-candle surge leaves a gap between candle 1 high and candle 3 low — a Fair Value Gap.',
        { q: 'A Fair Value Gap is:', options: ['A guaranteed fill', 'A gap from a fast move price may revisit', 'A doji', 'A volume spike only'], correct: 1, explain: 'An FVG is a gap from a fast move; price may revisit it, not guaranteed.' }),
      L('adv-3', 'Order Blocks',
        'An order block is the last opposing candle before a strong move — thought to mark where large orders were placed. It is a trader framework. Use it as a possible reaction zone with confirmation, never as a guaranteed level.',
        ['Last opposite candle before a strong move.', 'A possible reaction zone.', 'Framework — confirm, do not assume.'],
        'Before a strong bullish move, the last bearish candle is marked as a bullish order block.',
        { q: 'Order blocks are:', options: ['Guaranteed levels', 'A trader framework, possible reaction zones', 'Official exchange data', 'A type of doji'], correct: 1, explain: 'Order blocks are a trader framework — possible zones, not guaranteed.' }),
      L('adv-4', 'Wyckoff: Accumulation & Distribution',
        'Wyckoff theory describes phases where "smart money" accumulates (buys quietly at lows) or distributes (sells quietly at highs) before a major move. It is a framework for interpreting ranges. It is subjective and not a guaranteed map.',
        ['Accumulation = quiet buying at lows.', 'Distribution = quiet selling at highs.', 'A subjective framework.'],
        'A long base with repeated tests of support, then a breakout up — interpreted as Wyckoff accumulation.',
        { q: 'Wyckoff accumulation describes:', options: ['Selling at the top', 'Quiet buying at lows before a markup', 'A doji', 'A gap'], correct: 1, explain: 'Accumulation is quiet buying at lows before a markup.' }),
      L('adv-5', 'Distinguishing Concepts from Guarantees',
        'Many advanced concepts (order blocks, FVGs, Wyckoff) are trader frameworks — useful lenses, not market laws. Always distinguish established mechanics (liquidity, spread) from interpretive frameworks. Never treat a framework as a guarantee.',
        ['Frameworks are lenses, not laws.', 'Confirm with price action.', 'Never treat them as guaranteed.'],
        'A trader marks an order block but waits for a bullish reaction there — confirmation, not assumption.',
        { q: 'Advanced trader frameworks should be treated as:', options: ['Guaranteed rules', 'Lenses to confirm with price action', 'Official data', 'Useless'], correct: 1, explain: 'Frameworks are lenses — confirm with price action, never assume.' }),
    ],
  },
];

// Helper lookups
export const ALL_LESSONS = COURSES.flatMap((c) => c.lessons.map((l) => ({ ...l, courseId: c.id, courseTitle: c.title, courseColor: c.color, courseIcon: c.icon })));
export const COURSE_BY_ID = Object.fromEntries(COURSES.map((c) => [c.id, c]));
export const LESSON_BY_ID = Object.fromEntries(ALL_LESSONS.map((l) => [l.id, l]));

export function courseProgress(completed, course) {
  const total = course.lessons.length;
  const done = course.lessons.filter((l) => completed.includes(l.id)).length;
  return { done, total, pct: total ? Math.round((done / total) * 100) : 0, complete: done === total };
}

export function completedCourses(completed) {
  return COURSES.filter((c) => courseProgress(completed, c).complete).map((c) => c.id);
}

// Per-course quiz accuracy from quiz_history
export function courseAccuracy(quizHistory, courseId) {
  const attempts = (quizHistory || []).filter((a) => a.course_id === courseId);
  if (attempts.length === 0) return null;
  const totalQ = attempts.reduce((s, a) => s + (a.total || 0), 0);
  const correctQ = attempts.reduce((s, a) => s + (a.correct || 0), 0);
  return totalQ ? Math.round((correctQ / totalQ) * 100) : null;
}